---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: brandfrisch/ubuntu-16.04:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      r: /usr/local/src/ansible-lint-rules
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: 'None'
